# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pvz_service
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install migrate
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

    - name: Run migrations
      run: migrate -path ./migrations -database "postgres://postgres:postgres@localhost:5432/pvz_service?sslmode=disable" up

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v -cover ./cmd/integration

        go test -v -cover ./internal/handler
        go test -v -cover ./internal/middleware
        go test -v -cover ./internal/repository
        go test -v -cover ./internal/route

        go test -v -cover ./internal/service/auth
        go test -v -cover ./internal/service/product
        go test -v -cover ./internal/service/pvz
        go test -v -cover ./internal/service/reception
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: postgres  
        DB_NAME: pvz_service
        DB_SSLMODE: disable